#!/bin/sh

## Bspwm configurations
bspc monitor -d '1' '2' '3' '4' '5'
bspc config focus_follows_pointer   true
bspc config initial_polarity        second_child
bspc config border_width            4
bspc config window_gap              0
bspc config normal_border_color     "#707070"
bspc config focused_border_color    "#dee3e0"
bspc config presel_feedback_color   "#2c3939"
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config split_ratio             0.5
bspc config bottom_padding          32
bspc config top_padding             0
bspc config left_padding            0
bspc config right_padding           0

## Rules
bspc config external_rules_command ~/.config/bspwm/external-rules.sh
bspc rule -a 'Tor Browser' desktop='^4' follow=on state=floating
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a TelegramDesktop desktop='^3' follow=off
bspc rule -a code-oss desktop='^4' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a Sxiv state=floating center=true
bspc rule -a mpv follow=off state=floating center=true
bspc rule -a URxvt:urxvt_keys_help state=floating

## Autostart
hsetroot -solid black

killall -q -9 sxhkd dunst compton polybar
sxhkd &
dunst &
compton &
~/.config/polybar/launch.sh

sleep 1
dunstify "Notification" "Bspwmrc Loaded"
