#!/bin/sh

# h264_nvenc is for using gpu to encode
# use libx264 for cpu

# pactl list sources
AUDIO_CARD="alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
FILE="$HOME/Videos/record_$(date +%d-%m-%Y_%H:%M).mkv"

if pgrep ffmpeg; then
	killall ffmpeg
	notify-send "FFmpeg" "Gravação da tela finalizada!"
	exit 0
fi

set $(slop -q -o -f '%x %y %w %h')

notify-send "FFmpeg" "Gravação da tela iniciada!"

ffmpeg -s ${3}x${4} \
-f x11grab \
-i :0.0+${1},${2} \
-f pulse \
-ac 2 \
-i "$AUDIO_CARD" \
-c:v h264_nvenc \
-cq 19 \
-r 30 \
-c:a libopus \
-b:a 72k \
-y "$FILE" \
> /dev/null 2>&1
